"""empty message

Revision ID: 3106768e776e
Revises: None
Create Date: 2015-12-31 20:41:43.394747

"""

# revision identifiers, used by Alembic.
revision = '3106768e776e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beverage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('style', sa.String(length=100), nullable=True),
    sa.Column('abv', sa.Float(), nullable=True),
    sa.Column('ibu', sa.Integer(), nullable=True),
    sa.Column('srm', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=True),
    sa.Column('factor', sa.Integer(), nullable=True),
    sa.Column('total_volume', sa.Float(), nullable=True),
    sa.Column('beverage_id', sa.Integer(), nullable=True),
    sa.Column('current_volume', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['beverage_id'], ['beverage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tap')
    op.drop_table('beverage')
    ### end Alembic commands ###
